arch:
  - amd64
  - arm64

services:
  - docker

env:
  global:
    - IMAGE_NAME=tsuribori/shiprat

script:
  - docker build --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker ps -a

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${TRAVIS_CPU_ARCH}-latest"
  - if ["$TRAVIS_CPU_ARCH" == "arm64"]; then \
    docker manifest create "${IMAGE_NAME}:test-latest" \
    "${IMAGE_NAME}:arm64-latest" "${IMAGE_NAME}:amd64-latest" &&\
    docker manifest annonate "${IMAGE_NAME}:test-latest"\
    "${IMAGE_NAME}:arm64-latest" --arch arm64 &&\
    docker manifest annonate "${IMAGE_NAME}:test-latest"\
    "${IMAGE_NAME}:amd6-latest" --arch amd64 &&\
    docker manifest push "${IMAGE_NAME}:test-latest"; fi;

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:test-latest"
  on:
    branch: multi-architecture
