services:
  - docker

env:
  global:
    - IMAGE_NAME=tsuribori/shiprat

script:
  - docker build --cache-from "$IMAGE_NAME" --tag "$IMAGE_NAME" .

after_script:
  - docker ps -a

before_deploy:
  - echo "$REGISTRY_PASS" | docker login -u "$REGISTRY_USER" --password-stdin
  - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"

deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest"
  on:
    branch: master
